micronaut:
  application:
    name: micronaut-test

shedlock:
  defaults:
    lock-at-most-for: 1m

datasources:
  default:
    url: jdbc:h2:mem:devDb
    driverClassName: org.h2.Driver
    username: sa
    password: ''
    schema-generate: CREATE_DROP
    dialect: H2


